#cloud-config
users:
  - name: fisher
    groups: sudo
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC2owcpGR5YNKZh8iNfdyg6M/Tgmmmfr+lTbJG8ZjRHppLs1sCl/Uc+s9sfLMYzuvGz20oxICs/CtdViaYdw+mYNNa86XYJ6enbDythkCGeMYUKZZiis9XJ/E9+y/DtvVvdUaHeUyAqyGNgfN/4LXPEOUGRQiAraKt6a4wu8Rod4pUO8GgHPvXA34kqlzK6MutiRrtVimasGaMNYiKrptf3yrsWtw8DLmXsNocqZGXrYk4lHB+AMRjHbh25X17wHjKzvzZUSp+beM8Vj5rzxkzxDgcuXUoGCI3H3VlXRZ4JD9Ey/66a1WFAOltckszrMmoQPfBSMUJFUUXmpvufViM5
runcmd:
  - sed -i -e '/^Port/s/^.*$/Port 4444/' /etc/ssh/sshd_config
  - sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  - |
    apt-get install -y curl \
      wget \
      zsh \
      gcc \
      cmake \
      python3.8-dev \
      python3-pip \
      libssl-dev \
      make \
      mosh \
      libutempter-dev \
      zlib1g-dev \
      tmux \
  - |
    snap install --classic chezmoi \
    google-cloud-cli
  - sh -c "$(curl -fsSL https://starship.rs/install.sh)" -- --yes

