---
all:
  children:
    local:
      hosts:
        kermit-the-frog:
          ansible_connection: local
          ansible_user: michael
          ansible_python_interpreter: /usr/local/opt/python@3.8/bin/python3
        rosita:
          ansible_connection: local
          ansible_user: michael
          ansible_python_interpreter: /usr/local/opt/python@3.8/bin/python3
    digitalocean:
       hosts:
         website:
          ansible_port: 22
          ansible_user: michael
          ansible_python_interpreter: /usr/bin/python3
          size: s-1vcpu-3gb
          type: webserver
         streak-api:
          ansible_port: 22
          ansible_user: michael
          ansible_python_interpreter: /usr/bin/python3
          size: s-1vcpu-2gb
          type: worker
