---
all:
  children:
    local:
      hosts:
        cookie-monster:
          ansible_connection: local
          ansible_user: michael
          ansible_python_interpreter: /Users/michael/.pyenv/shims/python3.9
    digitalocean:
       hosts:
        website-small:
          ansible_port: 22
          ansible_user: michael
          ansible_python_interpreter: /usr/bin/python3
          size: s-1vcpu-1gb
          type: webserver
        rclone:
          ansible_port: 22
          ansible_user: michael
          ansible_python_interpreter: /usr/bin/python3
          size: s-4vcpu-8gb
          type: worker
