---
all:
  children:
    digitalocean:
       hosts:
        website-small:
          ansible_port: 22
          ansible_user: michael
          ansible_python_interpreter: /usr/bin/python3
          size: s-1vcpu-1gb
          type: webserver

