#! /usr/bin/env ansible-playbook

---
- hosts: all
  roles:
    - common
  gather_facts: yes
  vars:
   - user: "{{ ansible_env.LOGNAME }}"
   - home: "{{ ansible_env.HOME }}"
   - zsh_custom: "{{ home }}/.oh-my-zsh/custom"
   - git_dir: "{{ home }}/git"
   - python_site: "{{ home}}/.local/bin/"
   - pyenv_shims: "{{ home }}/.pyenv/shims"
   - civis_redshift_user: "michaelfisher"
  environment:
   - PATH: "{{ ansible_env.PATH }}"
