---
- hosts: all
  gather_facts: yes
  vars:
   - user: "{{ ansible_env.LOGNAME }}"
   - home: "{{ ansible_env.HOME }}"
   - zsh_custom: "{{ home }}/.oh-my-zsh/custom"
   - git_dir: "{{ home }}/git"
   - python_site: "{{ home}}/.local/bin/"
   - civis_redshift_user: "michaelfisher"

  tasks:
    - name: Install other things in Linux
      apt:
        name:
          - gnupg2
          - libpq-dev
          - zsh
          - powerline
          - fonts-powerline
          - awscli
          - python-dev
          - python3.6-dev
          - python3.7-dev
          - python3-pip
          - cmake
          - bzip2
          - gcc
          - libffi-dev
          - libyaml-dev
          - make
          - libssl-dev
      when: ansible_os_family == 'Debian'
      become: true
      become_method: sudo
      tags:
        - ruby

    - name: Upgrade Linux packages
      apt:
        upgrade: dist
      become: true
      become_method: sudo
      when: ansible_os_family == 'Debian'

    - import_tasks: brew.yml
      when: ansible_os_family == 'Darwin'
      tags:
        - brew

    - import_tasks: mas.yml
      when: ansible_os_family == 'Darwin'
      tags:
        - mas

    - import_tasks: files.yml
      tags:
        - files

    - import_tasks: ruby.yml
      tags:
        - ruby

    - import_tasks: python.yml
      tags:
        - python

