#! /usr/bin/env ansible-playbook

---
- hosts: local
  roles:
    - common
  gather_facts: yes
  vars:
   - user: "{{ ansible_env.LOGNAME }}"
   - home: "{{ ansible_env.HOME }}"
   - zsh_custom: "{{ home }}/.oh-my-zsh/custom"
   - git_dir: "{{ home }}/git"
   - python_site: "{{ home}}/.local/bin/"
   - civis_redshift_user: "michaelfisher"
   - brew_formula_list: "{{ lookup('file', 'templates/brew_formulas.txt') }}"
   - brew_cask_list: "{{ lookup('file', 'templates/brew_cask.txt') }}"
  environment:
   - PATH: "{{ ansible_env.PATH }}"
