---
- hosts: all
  gather_facts: yes
  vars:
   - user: "{{ lookup('env', 'LOGNAME') }}"
   - git_dir: "~/git"

  tasks:
    - name: Make git dir
      file: path="{{ git_dir }}" state=directory

    - name: Clone some repos
      git:
        repo: "ssh://git@github.com/{{ item.org }}/{{ item.name }}.git"
        dest: "{{ git_dir }}/{{ item.name }}"
        accept_hostkey: yes
        track_submodules: yes
        force: yes
      with_items:
        - { org: 'michaelefisher', name: 'dot-files' }
        - { org: 'powerline', name: 'fonts' }
        - { org: 'corybooker', name: 'serverless' }
        - { org: 'corybooker', name: 'aws-cloudformation' }
        - { org: 'corybooker', name: 'civis' }
        - { org: 'corybooker', name: 'cloudflare-workers-js' }
        - { org: 'wpcomvip', name: 'cory-booker' }
        - { org: 'corybooker', name: 'docker-wordpress-vip-go' }
        - { org: 'corybooker', name: 'dbt-projects' }

    - name: delete things that we don't want
      file:
        path: "~/{{ item }}"
        state: absent
      with_items:
        - '.bashrc'
        - '.vim'
        - '.vimrc'
        - '.bash_aliases'
        - '.bash-powerline.sh'
        - '.gitconfig'
        - '.tmux.conf'

    - name: link all the files
      file:
        src: "{{ git_dir }}/dot-files/{{ item }}"
        dest: "~/{{ item }}"
        state: link
        owner: "{{ user }}"
        force: yes
      with_items:
        - '.bashrc'
        - '.vimrc'
        - '.vim'
        - '.gitconfig'
        - '.bash-powerline.sh'
        - '.bash_aliases'
        - '.tmux.conf'

    - name: Write out bash_profile
      blockinfile:
        dest: "~/.bash_profile"
        insertafter: EOF
        create: yes
        content: "source ~/.bashrc"
      when: ansible_os_family == 'Darwin'

    - name: Install powerline shell fonts
      command: "./install.sh"
      args:
        chdir: "{{ git_dir }}/fonts"

    - name: Install other things in Linux
      apt:
        name: gnupg2
      when: ansible_os_family == 'Debian'

    - name: Install other things in macOS
      homebrew:
        name: ['adns','augeas','autoconf','automake','certbot','composer','coreutils','cscope','dbt','dialog','doctl','freetype','gdbm','gettext','ghostscript','giflib','gmp','gnupg','gnutls','icu4c','imagemagick','isl','jasper','jq','leptonica','libassuan','libevent','libffi','libgcrypt','libgpg-error','libidn2','libksba','libmpc','libpng','libpqxx','libtasn1','libtiff','libtool','libunistring','libusb','libyaml','lzo','macvim','mpfr','nettle','nmap','node','npth','nvm','openjpeg','pcre','pinentry','qt','rbenv','readline','redis','s3cmd','the_silver_searcher','tmux','xz','yarn']
      when: ansible_os_family == 'Darwin'
