---
- hosts: localhost
  gather_facts: no
  vars:
   - user: vagrant
   - git_dir: "/home/{{ user }}/git"

  tasks:

    - name: Clone some repos
      git:
        repo: "git@github.com:{{ item.org }}/{{ item.name }}.git"
        dest: "{{ git_dir }}/{{ item.name }}"
        accept_hostkey: yes
        track_submodules: yes
        force: yes
      with_items:
        - { org: 'democrats', name: 'ppapi-hfa' }
        - { org: 'democrats', name: 'mdAPI' }
        - { org: 'democrats', name: 'app-configuration-template' }
        - { org: 'democrats', name: 'packer-python-base-ami' }
        - { org: 'democrats', name: 'iwillvote-locate' }
        - { org: 'michaelefisher', name: 'dot-files' }
        - { org: 'HillaryClinton', name: 'pocket-protector' }
        - { org: 'banga', name: 'powerline-shell' }

    - name: Change owner and group for git dir
      file:
        path: "{{ git_dir }}"
        owner: "{{ user }}"
        group: "{{ user }}"
        recurse: yes

    - name: delete things that we don't want
      file:
        path: "/home/{{ user}}/{{ item }}"
        state: absent
      with_items:
        - '.bashrc'
        - '.vim'
        - '.vimrc'

    - name: link all the files
      file:
        src: "{{ git_dir }}/dot-files/{{ item }}"
        dest: "/home/{{ user }}/{{ item }}"
        state: link
        owner: "{{ user }}"
        group: "{{ user }}"
        force: yes
      with_items:
        - '.bashrc'
        - '.vimrc'
        - '.vim'
        - '.gitconfig'

    - name: Copy powerline shell config
      copy: src="{{ git_dir }}/powerline-shell/config.py.dist" dest="{{ git_dir }}/powerline-shell/config.py" owner="{{ user }}" group="{{ user }}"

    - name: Install powerline shell
      command: "./install.py"
      args:
        chdir: "{{ git_dir }}/powerline-shell"
      become: true
      become_user: "{{ user }}"

    - name: Install VirtualBox and Vagrant
      apt:
        deb: "{{ item }}"
      with_items:
        - http://download.virtualbox.org/virtualbox/5.1.18/virtualbox-5.1_5.1.18-114002~Ubuntu~xenial_amd64.deb
        - https://releases.hashicorp.com/vagrant/1.9.3/vagrant_1.9.3_x86_64.deb

    - name: Install rvm and install ruby 2.2.0
      shell: "{{ item }}"
      with_items:
        - "curl -sSL https://get.rvm.io | bash"

