---
- hosts: all
  gather_facts: yes
  vars:
   - user: "{{ lookup('env', 'LOGNAME') }}"
   - git_dir: "~/git"

  tasks:
    - name: Make git dir
      file: path="{{ git_dir }}" state=directory

    - name: Clone some repos
      git:
        repo: "git@github.com:{{ item.org }}/{{ item.name }}.git"
        dest: "{{ git_dir }}/{{ item.name }}"
        accept_hostkey: yes
        track_submodules: yes
        force: yes
        key_file: "/home/{{ user }}/.ssh/walter"
      with_items:
        - { org: 'michaelefisher', name: 'dot-files' }

    - name: Change owner and group for git dir
      file:
        path: "{{ git_dir }}"
        owner: "{{ user }}"
        recurse: yes

    - name: delete things that we don't want
      file:
        path: "~/{{ item }}"
        state: absent
      with_items:
        - '.bashrc'
        - '.vim'
        - '.vimrc'
        - '.bash_aliases'
        - '.bash-powerline.sh'
        - '.gitconfig'
        - '.tmux.conf'

    - name: link all the files
      file:
        src: "{{ git_dir }}/dot-files/{{ item }}"
        dest: "~/{{ item }}"
        state: link
        owner: "{{ user }}"
        force: yes
      with_items:
        - '.bashrc'
        - '.vimrc'
        - '.vim'
        - '.gitconfig'
        - '.bash-powerline.sh'
        - '.bash_aliases'
        - '.tmux.conf'

    - name: Write out bash_profile
      blockinfile:
        dest: "~/.bash_profile"
        insertafter: EOF
        create: yes
        content: "source ~/.bashrc"
      when: ansible_os_family == 'Darwin'

    - name: Install other things in Linux
      apt:
        name: "{{ item }}"
      with_items:
        - gnupg2
        - awscli
      when: ansible_os_family == 'Debian'

    - name: Install other things in macOS
      apt:
        name: "{{ item }}"
      with_items:
        - gnupg2
        - awscli
      when: ansible_os_family == 'Debian'

    - name: Copy dynamic profiles into iTerm2
      copy:
        src: "tmux_profiles.json"
        dest: "~/Library/Application Support/iTerm2/DynamicProfiles/tmux_profiles.json"
      when: ansible_os_family == 'Darwin'

