---
- name: Install vim with python
  homebrew:
    name: vim
    state: present
    install_options: with-python
  tags:
    - homebrew

- name: Tap some repos
  homebrew_tap:
    name: "{{ item.name }}"
    state: present
  with_items:
    - { name: homebrew/cask }
    - { name: homebrew/cask-drivers }
    - { name: homebrew/cask-versions }
  tags:
    - homebrew

# Install and remove homebrew formulas

- name: Install homebrew items
  homebrew:
    name: "{{ lookup('file', 'templates/brew_requirements.txt') }}"
    update_homebrew: yes
    state: upgraded
    upgrade_all: yes
  tags:
    - homebrew

- name: Uninstall homebrew items
  homebrew:
    name: "{{ lookup('file', 'templates/brew_uninstall.txt') }}"
    state: absent
  tags:
    - homebrew

# Install and remove homebrew formulas

- name: Install homebrew cask items
  homebrew:
    name: "{{ lookup('file', 'templates/brew_cask_requirements.txt') }}"
    state: upgraded
    upgrade_all: yes
  tags:
    - homebrew

- name: Uninstall homebrew cask items
  homebrew:
    name: "{{ lookup('file', 'templates/brew_cask_uninstall.txt') }}"
    state: absent
    sudo_password: "{{ ansible_become_password }}"
  tags:
    - homebrew

- name: Where is the cache?
  command: "brew --cache"
  changed_when: True
  register: homebrew_cache_path
  tags:
    - homebrew
    - homebrew_cask
  notify:
    - "Homebrew cache clear"
