---
- name: Tap some repos
  homebrew_tap:
    name: "{{ item.name }}"
    state: present
  with_items:
    - { name: homebrew/cask }
    - { name: homebrew/cask-drivers }

- name: Install homebrew items
  homebrew:
    name: "{{ brew_formual_list }}"
    update_homebrew: yes
    upgrade_all: yes
  tags:
    - homebrew

- name: Install homebrew cask items
  homebrew_cask:
    name: "{{ item }}"
    state: upgraded
  loop: "{{ brew_cask_list }}"
  tags:
    - homebrew
    - homebrew_cask

- name: Where is the cache?
  command: "brew --cache"
  register: homebrew_cache_path
  tags:
    - homebrew
  notify:
    - "homebrew_cache_clear"
