---
- name: Install vim with python
  homebrew:
    name: vim
    state: latest
    install_options: with-python
  tags:
    - homebrew

- name: Tap some repos
  homebrew_tap:
    name: "{{ item.name }}"
    state: present
  with_items:
    - { name: homebrew/cask }
    - { name: homebrew/cask-drivers }
    - { name: homebrew/cask-versions }
  tags:
    - homebrew
    - homebrew_cask

- name: Install homebrew items
  homebrew:
    name: "{{ brew_formula_list }}"
    update_homebrew: yes
    state: latest
    upgrade_all: yes
  tags:
    - homebrew

- name: Install homebrew cask items
  homebrew_cask:
    name: "{{ brew_cask_list }}"
    state: present
    greedy: yes
    upgrade_all: yes
  tags:
    - homebrew
    - homebrew_cask

- name: Where is the cache?
  command: "brew --cache"
  register: homebrew_cache_path
  tags:
    - homebrew
    - homebrew_cask
  notify:
    - "homebrew_cache_clear"
