---
- name: Tap some repos
  homebrew_tap:
    name: "{{ item.name }}"
    state: present
  with_items:
    - { name: homebrew/cask }
    - { name: homebrew/cask-drivers }

- name: Install homebrew items
  homebrew:
    name: ['awscli', 'adns','augeas','autoconf','automake','reattach-to-user-namespace','pgcli','coreutils','cscope','cmake','dialog','doctl','freetype','gdbm','gettext','giflib', 'git-lfs', 'gmp','gnupg','gnutls','icu4c','isl','irssi','jasper','jq','leptonica','libassuan','libevent','libffi','libgcrypt','libgpg-error','libidn2','libksba','libmpc','libpng','libpqxx','libtasn1','libtiff','libtool','libunistring','libusb','libyaml','lzo','kubernetes-cli','mpfr','nettle','nmap','node','npth','nvm','mas','macvim','pcre','pinentry','qt','rbenv','readline','rclone','s3cmd','telnet','the_silver_searcher','tmux','xz','yarn','watch']
    update_homebrew: yes
    upgrade_all: yes
  tags:
    - homebrew

- name: Install homebrew cask items
  homebrew_cask:
    name: "{{ item.name }}"
    state: upgraded
  with_items:
    - { name: omnidisksweeper }
    - { name: keybase }
    - { name: google-cloud-sdk }
#    - { name: docker } Use https://hub.docker.com/editions/community/docker-ce-desktop-mac/
  tags:
    - homebrew

- name: Where is the cache?
  command: "brew --cache"
  register: homebrew_cache_path
  tags:
    - homebrew
  notify:
    - "homebrew_cache_clear"
