---
- name: Install other things in Linux
  apt:
    name:
      - gnupg2
      - libpq-dev
      - powerline
      - fonts-powerline
      - awscli
      - bzip2
      - libffi-dev
      - libyaml-dev
      - silversearcher-ag
  when: ansible_os_family == 'Debian'
  become: true
  become_method: sudo
  tags:
    - files,ruby

- name: Install snaps
  snap:
    name: node
    classic: yes
  when: ansible_os_family == 'Debian'
  become: true
  become_method: sudo
  tags:
    - files

- name: Upgrade Linux packages
  apt:
    upgrade: dist
  become: true
  become_method: sudo
  when: ansible_os_family == 'Debian'

- include: brew.yml
  when: ansible_os_family == 'Darwin'
  tags:
    - homebrew

- include: files.yml
  tags:
    - files

- include: ruby.yml
  tags:
    - ruby

- include: python.yml
  tags:
    - python

