---
- name: ensure website dir
  file:
    path: "{{ item }}"
    state: directory
    owner: root
  with_items:
    - "/var/www/"
  become: true
  become_method: sudo

- name: sync website
  git:
    repo: "ssh://git@github.com/michaelefisher/website.git"
    dest: "/var/www"
    accept_hostkey: yes
    track_submodules: no
    force: yes

- name: install letsencrypt
  snap:
    name: certbot
    classic: yes

- name: install python certbot dns plugin
  apt:
    name: python-certbot-dns
