---
- name: Download nvm
  get_url:
    url: "https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh"
    dest: "/tmp/install.sh"
    mode: "0555"
  become: true
  become_method: sudo

- name: Run nvm install
  shell: >
    /bin/bash -c "./tmp/install.sh || true"
  changed_when: true

- name: Install node
  shell: >
    /bin/bash -c "source ~/.nvm/nvm.sh && nvm install node || true"
    creates="{{ home }}/.nvm/alias"
  changed_when: true

