name: Lint ansible files

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Important: This sets up your GITHUB_WORKSPACE environment variable
    - uses: actions/checkout@v2
      with:
        path: "main"

    - name: Lint Ansible Playbook
      # replace "master" with any valid ref
      uses: ansible/ansible-lint-action@master
      with:
        targets: |
          main/roles/common/tasks/*
          main/roles/common/handlers/*
          main/roles/webservers/tasks/*

